AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
